### ISSUE TITLE
Default RewriteRule does not work

### ISSUE THREAD

**Issue by corro** [studer-raimann/LiveVoting#9]
The default RewriteRule, as stated in the README and documentation, does not work. First, the URL should be relative to the base URL:

```
RewriteRule ^/vote([|/|/0-9]*)$ /Customizing/global/plugins/Services/Repository/RepositoryObject/LiveVoting/pin.php?pin=$1 [L]
```

Notice the extra slashes before "vote" and "Customizing". Second, the Rule does not handle links with "pin" as GET parameter, but that's what the links in the QR fields contain. So a correct RewriteRule would look like this:

```
RewriteRule ^/vote(\?pin=[0-9]*)?$ /Customizing/global/plugins/Services/Repository/RepositoryObject/LiveVoting/pin.php$1 [L]
```

**Comment by srgitlab** [comment]
Moved to Jira
